version: "3"

services:
  api-find-a-friend:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRESQL_DATABASE=findafriendapi
